spring:
  application:
    name: calculation-service
  cloud:
    config:
      uri: http://localhost:8888  # URL of the Spring Cloud Config Server
  profiles:
    active: default  # Activate the default profile
  datasource:
    url: jdbc:mysql://localhost:3306/calculation_db
    username: root
    password: Pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
